config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'pages#home'
  get 'about', to: 'pages#about'

  devise_for :users

  resources :categories do
    resources :contents
  end

  resources :testimonials, only: [ :index, :edit, :update ]
  resources :about
end

app/models/about.rb
class About < ApplicationRecord
  validates_presence_of :name
  validates_presence_of :photo
  validates_presence_of :bio
  validates_presence_of :title

  default_scope { where(active: true) }

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :contents

  validates_presence_of :name
  validates_presence_of :description
  default_scope { where(active: true)}
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :category

  validates_presence_of :info_label
  validates_presence_of :category
  default_scope { where(active: true)}

  def self.search(search)
    where("info_label ILIKE ? OR info_text ILIKE ?", "%#{search}%", "%#{search}%")
  end

  def self.sort_by_date
    order(created_at: :desc)
  end
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :quote
  validates_presence_of :photo

  default_scope { where(active: true)}

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]

  def index
    @categories = Category.all
    @categories_top_9 = Category.order("created_at DESC").take(9)
  end

  def show
    if params[:search]
      @contents = Content.search(params[:search]).order("created_at DESC")
    else
      @contents = @category.contents
    end
  end


  private
    def category_params
      params.require(:category).permit(:name, :description, :photo, :active)
    end

    def set_category
      @category = Category.find(params[:id])
    end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

  def index
    @contents = Content.all
  end

  def show
    @content =  Content.find(params[:id])
  end


  private
    def content_params
      params.require(:content).permit(:info_label, :info_text, :video, :photo,
      :active, :website_link, :category_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @categories = Category.all
    @testimonials = Testimonial.all
  end

  def about
    @abouts=About.all
  end
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  def index
    @testimonials = Testimonial.all
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/categories/index.html.erb
<div class="text-center page-title">
  <h2>Effects of Music</h2>
</div>
<div class="container">
  <% @categories_top_9.each do |category| %>
  <a href="<%=category_path(category.id)%>">
    <div class="col-md-4">
      <div class="card text-center">
        <div class="card-img-top img-responsive" style="background-image: url('<%= category.photo %>')">
          <div class="card-border">
            <h3><%= category.name %></h3>
            <h5><%= category.description %></h5>
          </div>
        </div>
      </div>
    </div>
  </a>
  <% end %>
</div>

app/views/categories/show.html.erb
<div class=" text-center page-title">
  <h2><%= @category.name %></h2>
  <h5><%= @category.description %></h5>
</div>
<div class="container">
  <div class="col-md-12">

    <% media_left = false %>
    <% @contents.each do |content| %>
    <div class="media-container">

      <a href="<%= content.website_link != '' && content.website_link != nil ? content.website_link : category_content_path(@category, content) %>" target="<%= content.website_link != '' && content.website_link != nil ? '_blank' : '_self' %>">
        <div class="media <%= media_left == false ? 'white-highlighter' : 'orange-hightlighter' %>">
          <!-- Left thumbnail -->
          <% if !media_left %>
          <div class="media-left">
            <div class="media-thumbnail" style="background-image: url('<%= content.photo != '' ? content.photo : " http://budapesttimes.hu/wp-content/themes/newsroom14/img/placeholder.png" %>')"></div>
          </div>
          <% end %>
          <div class="media-body">
            <h4 class="media-heading"><%= content.info_label.first(150) %>...</h4>
            <hr>
            <p><%= content.info_text.first(250) %>...</p>
          </div>
          <!-- Right thumbnail -->
          <% if media_left %>
          <div class="media-right">
            <div class="media-thumbnail" style="background-image: url('<%= content.photo != '' ? content.photo : " http://budapesttimes.hu/wp-content/themes/newsroom14/img/placeholder.png" %>')"></div>
          </div>
          <% end %>
        </a>
      </div>

      <% media_left = !media_left %>

    </div>
    <!-- media container -->
    <% end %>
    <!-- media -->
  </div>
  <!-- col -->
</div>
<!-- container -->

app/views/contents/show.html.erb
<div class=" text-center page-title">
  <h2><%= @content.info_label %></h2>
  <h5></h5>
</div>
<div class="container">
  <div class="col-md-12">
    <div class="video-container text-center">
      <% if @content.video != '' %>
      <iframe width="853" height="480" src="<%= @content.video %>" frameborder="0" allowfullscreen></iframe>
      <% end %>
    </div>
    <div class="media white-highlighter">
      <div class="media-body">
        <h4 class="media-heading">
          <%= @content.info_label %></h4>
        <hr>
        <p>
          <%= @content.info_text %>
        </p>
      </div>
    </div>
    <!-- col -->
  </div>
  <!-- container -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Allerta+Stencil" rel="stylesheet">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Barrio" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <%= yield %>
    <%= render 'shared/footer' %>
    <script>
    $('.play').click(function(){
        var $this = $(this);
        var id = $this.attr('id').replace(/btn/, '');
        $this.toggleClass('active');
        if($this.hasClass('active')){
            $this.text("\u2016");
            $('audio[id^="sound"]')[id-1].play();
        } else {
            $this.text("\u25B6");
            $('audio[id^="sound"]')[id-1].pause();
        }
    });
    </script>
  </body>
</html>

app/views/pages/about.html.erb
<div class="text-center page-title">
  <div class="container">
    <div class="right-border">
      <h2>
        <i class="fa fa-address-card-o" aria-hidden="true"></i>
        <%= @abouts.size != 0 && @abouts.size <2 ? 'About Me' : 'About Us'%>
      </h2>
      <h5>Behind the scenes</h5>
    </div>
  </div>
</div>

<div class="container about">
  <% @iteration = false %>
  <% @abouts.each do |about| %>

  <% if @iteration == false %>
  <!-- photo on left -->
  <div class="row white-highlighter">
    <div class="col-md-3 text-center">
      <div class="about-img" style="background-image:url('<%= about.photo %>')"></div>
      <h3><%= about.name %></h3>
      <h5><%= about.title %></h5>
    </div>
    <div class="col-md-9">
      <p><i><%= about.motto %></i></p>
      <hr>
      <p><%= about.bio %></p>
    </div>
  </div>
<% else %>
  <!-- photo on right -->
  <div class="row orange-hightlighter">
    <div class="col-md-9">
        <p><i><%= about.motto %></i></p>
        <hr>
      <p><%= about.bio %></p>
    </div>
    <div class="col-md-3 text-center">
      <div class="about-img" style="background-image:url('<%= about.photo %>')"></div>
      <h3><%= about.name %></h3>
      <h5><%= about.title %></h5>
    </div>
  </div>

  <% end %>
  <% @iteration == false ? @iteration = true : @iteration = false %>
  <% end %>

</div>

app/views/pages/home.html.erb
<div class="container text-center homepage-banner-title">
<h2>Music is already being used as medicine all around the world </h2>
<hr>
</div>
<%= render 'shared/carousel' %>
<div class="container">
<hr>
</div>
<div class="text-center">
<a href="<%= categories_path %>" class="btn btn-second btn-homepage">See More Effects</a>
  </div>
<%= render 'shared/testimonials' %>

app/views/shared/_carousel.html.erb
<div id="categories" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner" role="listbox">
    <% @categories.in_groups_of(3, false) do |category_group| %>
    <div class="item">
      <div class="container">
        <div class="row">
          <% category_group.each do |category| %>
          <a href="<%=category_path(category.id)%>">
            <div class="col-md-4">
              <div class="card text-center">
                <div class="card-img-top img-responsive" style="background-image: url('<%= category.photo %>')">
                  <div class="card-border">
                    <h3><%= category.name %></h3>
                    <h5><%= category.description %></h5>
                  </div>
                </div>
              </div>
            </div>
          </a>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <a class="left carousel-control" href="#categories" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#categories" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<script type="text/javascript">
  $('.carousel').find('.item').first().addClass('active')
</script>

app/views/shared/_footer.html.erb
<footer id="contact">
  <div class="container">
    <p>&nbsp;</p>
    <div class="col-md-12 center">
      <h4>Contact</h4>
      <ul class="list-unstyled">
        <li class="padding-bottom">
          <a href="/about" id="footer-a-contact-about" class="btn btn-second li-width">
            About
          </a>
        </li>
        <li class="padding-bottom">
          <a id="footer-a-contact-mail" href="mailto:info@musicasmedicine.nl" class="btn btn-second li-width" target="_blank">
            info@musicasmedicine.nl
          </a>
        </li>
        <li>
          <a id="footer-a-contact-phone" href="tel:+31633919249" class="btn btn-second li-width">
            Call
            <i class="fa fa-phone" aria-hidden="true"></i>
          </a>
        </li>
      </ul>
    </div>
    <div class="col-md-12 foot-social text-center">
      <h5>Follow us on</h5>
      <ul class="list-inline">
        <li>
          <a class="btn btn-first full-radius" href="https://www.facebook.com/Music-as-Medicine-1025666594159371/" target="_blank">
            <i class="fa fa-facebook-square fa-2x" aria-hidden="true"></i>
            <span class="sr-only">Facebook</span>
          </a>
        </li>
        <li>
          <a class="btn btn-first full-radius" href="https://www.linkedin.com/in/astrid-gribnau-md-8534a917/" target="_blank">
            <i class="fa fa-linkedin-square fa-2x" aria-hidden="true"></i>
            <span class="sr-only">LinkedIn</span>
          </a>
        </li>
        <li>
          <a class="btn btn-first full-radius" href="https://twitter.com/AstridGribnau" target="_blank">
            <i class="fa fa-twitter fa-2x" aria-hidden="true"></i>
            <span class="sr-only">Twitter</span>
          </a>
        </li>
      </ul>
    </div>
  </div>
  <div class="text-center">
    <p class="copy">© 2017 Music As Medicine</p>
    <a>&nbsp;</a>
  </div>
</footer>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="container">
    <div class="headbar">
    <%= render 'shared/navbar' %>
    </div>
    <!-- Headbar -->
    <div class="row banner-title text-center">
      <b>
        <h1>Music as Medicine</h1>
      </b>
      <h5>Where neuroscience meets healthcare</h5>
      <a href="<%= about_path %>" class="btn btn-trans">About</a>
      <p>&nbsp;</p>
    </div>
    <!-- Banner-title -->
  </div>
  <!-- Container -->
  <% if params[:id] != nil && current_page?(category_path{params[:id]}) %>
  <div class="headsearch">
    <div class="col-md-6 col-md-offset-3">
      <%= form_tag(@category, method: "get", id: "search-form", class: "input-group") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search", class: "form-control " %>
      <span class="input-group-btn">
        <%= submit_tag "Search", class: "btn btn-second" %>
      </span>
      <% end %>
    </div>
  </div>
  <% end %>
  <!-- Headsearch -->
</header>

app/views/shared/_navbar.html.erb
<nav class="navbar ">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar">___</span>
        <span class="icon-bar">___</span>
        <span class="icon-bar">___</span>
      </button>
      <a class="brand" href="<%= root_path %>"><h2>
        <i class="fa fa-stethoscope " style="font-size:48px;color:white"></i></h2>
      </a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="/" class="btn btn-second btn-width navbar-btn">
            <i class="fa fa-home" aria-hidden="true"></i>
            Home</a>
        </li>
        <li>
          <a href="/#testimonials" class="btn btn-second btn-width navbar-btn">
            <i class="fa fa-pencil" aria-hidden="true"></i>
            Testimonials</a>
        </li>
        <li>
          <a href="<%= categories_path %>" class="btn btn-second btn-width navbar-btn">
            <i class="fa fa-music" aria-hidden="true"></i>
            Music Effects</a>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/shared/_testimonials.html.erb
<div class="testimonial-container tex-center">
<div class="container content text-center" id="testimonials">
  <h1 class="testimonial-title">Professional Evidence </h1>
  <hr>
  <% @testimonials.each do |testimonial| %>
  <div class="col-md-4">
    <div class="testimonials">
      <div class="active item">
        <div class="carousel-info">
          <%= image_tag testimonial.photo, class: 'pull-left' %>
          <div class="pull-left">
            <span class="testimonials-name"><%= testimonial.full_name %></span>
            <span class="testimonials-post"><%= testimonial.title %></span>
          </div>
        </div>
        <blockquote>
          <p><%= testimonial.quote%></p>
        </blockquote>
      </div>
    </div>
  </div>
  <% end %>
</div>
</div>